/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import UTIL.koneksi;

/**
 *
 * @author EKA SAPUTRA
 */
public class viewCariBarang extends javax.swing.JFrame {

    koneksi koneksi = new koneksi();
    /**
     * Creates new form viewCariBarang
     */
    public viewCariBarang() {
        initComponents();
        dataTable();
    }



    private void dataTable() {
        koneksi.koneksidatabase();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Jenis");
        tabel.addColumn("Jumlah");

        TBL_CARIBARANG.setModel(tabel);
        try {
            String sql = "select * from tbl_barang";

            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("jumlah")
                });
                TBL_CARIBARANG.setModel(tabel);
            }
        } catch (Exception eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        JT_CARI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_CARIBARANG = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("CARI BARANG  :");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        JT_CARI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JT_CARIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JT_CARIKeyReleased(evt);
            }
        });
        jDesktopPane1.add(JT_CARI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, -1));

        TBL_CARIBARANG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_CARIBARANG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_CARIBARANGMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TBL_CARIBARANGMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_CARIBARANG);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 370, 220));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBL_CARIBARANGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_CARIBARANGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBL_CARIBARANGMouseClicked

    private void TBL_CARIBARANGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_CARIBARANGMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBL_CARIBARANGMousePressed

    private void JT_CARIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_CARIKeyReleased
        // TODO add your handling code here:
        koneksi.koneksidatabase();
        String nama = JT_CARI.getText();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Jenis");
        tabel.addColumn("Jumlah");

        TBL_CARIBARANG.setModel(tabel);
        try {
            String sql = "select * from tbl_barang where nama like '%" + nama + "%'";

            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("jumlah")
                });
                TBL_CARIBARANG.setModel(tabel);
            }
        } catch (Exception eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }//GEN-LAST:event_JT_CARIKeyReleased

    private void JT_CARIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_CARIKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_CARIKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCariBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_CARI;
    private javax.swing.JTable TBL_CARIBARANG;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
