/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import UTIL.koneksi;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import CONTROLLER.ControllerBarang;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import MODEL.ModelBarang;
import UTIL.koneksi;
/**
 *
 * @author EKA SAPUTRA
 */
public class viewBarang extends javax.swing.JFrame {
 koneksi koneksi = new koneksi();
    ControllerBarang cb = new ControllerBarang();
    ModelBarang mb = new ModelBarang();
    /**
     * Creates new form viewBarang
     */
    public viewBarang() {
        initComponents();
        dataTable();
    }
  private void baru() {
        BTN_BARU.setEnabled(false);
        BTN_SIMPAN.setEnabled(true);
        BTN_UBAH.setEnabled(false);
        BTN_HAPUS.setEnabled(false);
        JT_NAMA.setEditable(true);
        JT_JENIS.setEditable(true);
        JT_JUMLAH.setEditable(true);
        bersih();
    }
    
    private void bersih(){
        JT_ID.setText("");
        JT_NAMA.setText("");
        JT_JENIS.setText("");
        JT_JUMLAH.setText("");
        JT_NAMA.requestFocus();
    }
    
    private void ubahDanHapus(){
        BTN_SIMPAN.setEnabled(false);
        BTN_HAPUS.setEnabled(true);
        BTN_UBAH.setEnabled(true);
        JT_NAMA.setEditable(true);
        JT_JENIS.setEditable(true);
        JT_JUMLAH.setEditable(true);
    }
    
    private void dataTable(){
        koneksi.koneksidatabase();
        
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Jenis");
        tabel.addColumn("Jumlah");
        
        TBL_BARANG.setModel(tabel);
        try {
            String sql = "select * from tbl_barang";
            
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("ID"),
                    res.getString("NAMA"),
                    res.getString("JENIS"),
                    res.getString("JUMLAH")
                });
                TBL_BARANG.setModel(tabel);
            }
        } catch (Exception eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JT_JUMLAH = new javax.swing.JTextField();
        JT_JENIS = new javax.swing.JTextField();
        JT_NAMA = new javax.swing.JTextField();
        JT_ID = new javax.swing.JTextField();
        BTN_TUTUP = new javax.swing.JButton();
        BTN_BERSIH = new javax.swing.JButton();
        BTN_UBAH = new javax.swing.JButton();
        BTN_HAPUS = new javax.swing.JButton();
        BTN_BARU = new javax.swing.JButton();
        BTN_SIMPAN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_BARANG = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" ID BARANG         :");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("JENIS BARANG     :");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 102, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("NAMA BARANG    :");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 71, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("JUMLAH BARANG :");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 135, -1, -1));
        jDesktopPane1.add(JT_JUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 20));
        jDesktopPane1.add(JT_JENIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 20));
        jDesktopPane1.add(JT_NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, 20));

        JT_ID.setEnabled(false);
        jDesktopPane1.add(JT_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 20));

        BTN_TUTUP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_TUTUP.setText("TUTUP");
        BTN_TUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TUTUPActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_TUTUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, 40));

        BTN_BERSIH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_BERSIH.setText("BERSIH");
        BTN_BERSIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BERSIHActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_BERSIH, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 80, 40));

        BTN_UBAH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_UBAH.setText("UBAH");
        BTN_UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UBAHActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_UBAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, 40));

        BTN_HAPUS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_HAPUS.setText("HAPUS");
        BTN_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPUSActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_HAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 80, 40));

        BTN_BARU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_BARU.setText("BARU");
        BTN_BARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BARUActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_BARU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 80, 40));

        BTN_SIMPAN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_SIMPAN.setText("SIMPAN");
        BTN_SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMPANActionPerformed(evt);
            }
        });
        jDesktopPane1.add(BTN_SIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 40));

        TBL_BARANG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_BARANG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_BARANGMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBL_BARANG);

        jDesktopPane1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 110));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMPANActionPerformed
        // TODO add your handling code here:
         try {
            String nama = JT_NAMA.getText();
            String jenis = JT_JENIS.getText();
            int jumlah = Integer.parseInt(JT_JUMLAH.getText());
            
            mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);
            cb.simpanData(mb);
            dataTable();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan ANgka");
            JT_NAMA.setText("");
            JT_NAMA.requestFocus();
        }
    }//GEN-LAST:event_BTN_SIMPANActionPerformed

    private void BTN_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPUSActionPerformed
        // TODO add your handling code here:
         try {
            int id = Integer.parseInt(JT_ID.getText());
            
            mb.setId(id);
            cb.hapusData(mb);
            
            dataTable();
            bersih();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama");
        }
    }//GEN-LAST:event_BTN_HAPUSActionPerformed

    private void BTN_BARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BARUActionPerformed
        // TODO add your handling code here:
        baru();
    }//GEN-LAST:event_BTN_BARUActionPerformed

    private void BTN_UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UBAHActionPerformed
        // TODO add your handling code here:                                           
 try {
            int id = Integer.parseInt(JT_ID.getText());
            String nama = JT_NAMA.getText();
            String jenis = JT_JENIS.getText();
            int jumlah = Integer.parseInt(JT_JUMLAH.getText());
            
            mb.setId(id);
            mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);
            cb.ubahData(mb);
            
            bersih();
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama");
        }
   
    }//GEN-LAST:event_BTN_UBAHActionPerformed

    private void TBL_BARANGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_BARANGMouseClicked
        // TODO add your handling code here:
         ubahDanHapus();
        try {
            int baris = TBL_BARANG.getSelectedRow();
            JT_ID.setText(TBL_BARANG.getValueAt(baris, 0).toString());
            JT_NAMA.setText(TBL_BARANG.getValueAt(baris, 1).toString());
            JT_JENIS.setText(TBL_BARANG.getValueAt(baris, 2).toString());
            JT_JUMLAH.setText(TBL_BARANG.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            System.err.println("Error : " + e);
        }
    }//GEN-LAST:event_TBL_BARANGMouseClicked

    private void BTN_BERSIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BERSIHActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BTN_BERSIHActionPerformed

    private void BTN_TUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TUTUPActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTN_TUTUPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BARU;
    private javax.swing.JButton BTN_BERSIH;
    private javax.swing.JButton BTN_HAPUS;
    private javax.swing.JButton BTN_SIMPAN;
    private javax.swing.JButton BTN_TUTUP;
    private javax.swing.JButton BTN_UBAH;
    private javax.swing.JTextField JT_ID;
    private javax.swing.JTextField JT_JENIS;
    private javax.swing.JTextField JT_JUMLAH;
    private javax.swing.JTextField JT_NAMA;
    private javax.swing.JTable TBL_BARANG;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
